spring:
  application:
    name: recipe-info-service
  cloud:
    config:
      uri: configuration-server
  data:
    mongodb:
      uri: mongodb+srv://home:brew@homebrew.giq7q.gcp.mongodb.net/<dbname>?retryWrites=true&w=majority
      database: recipes
server:
  port: 8084