spring:
  application:
    name: hops-info-service
  data:
    mongodb:
      uri: mongodb+srv://home:brew@homebrew.giq7q.gcp.mongodb.net/<dbname>?retryWrites=true&w=majority
      database: hops
server:
  port: 8082